/* Tarefa 2
{ + & - VALOR: 1, * & / VALOR: 2, ( VALOR: 0}
° - SE A PRIORIDADE DE QUEM ESTIVER NO TOPO FOR MAIOR OU IGUAL EU DESEMPILHO E EMPILHO QUEM ESTIVER TENTANDO ENTAR
° - SE QUEM ESTA TENTANDO ENTRAR TIVER PRIORIDADE MAIOR DO QUE O TOPO EU EMPILHO

1. D - B + C = 11

DB-C+
82-5+
11

2. A * B + C - D = 1

AB*C+D-
11*1+1-
1

3. (A+B) *C-D*F+C = 2

AB+C*DF*C+-

4. (A-2*(B+C)-D*E)*F 
( - ( - *
A2*BC+DE*F*--


*/


